theme = "ayu_dark"

[editor]
scrolloff = 10
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-line-ending", "file-encoding"]

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true

[keys.normal]
"n" = "move_line_down"
"e" = "move_line_up"
"i" = "move_char_right"

"j" = "search_next"
"k" = "move_next_word_end"
"l" = "insert_mode"

"J" = "search_prev"
"K" = "move_next_long_word_end"
"L" = "insert_at_line_start"

[keys.insert]
"C-c" = "normal_mode"

# [keys.normal.minor.window]
# "n" = "jump_view_down"
# "e" = "jump_view_up"
# "i" = "jump_view_right"

# "N" = "swap_view_down"
# "E" = "swap_view_up"
# "I" = "swap_view_right"
